export const data = {
  albums: {
    href:
      "https://api.spotify.com/v1/search?query=eminem+&type=album&offset=0&limit=10",
    items: [
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2cWBwpqMsDJC1ZUwz813lo",
        },
        href: "https://api.spotify.com/v1/albums/2cWBwpqMsDJC1ZUwz813lo",
        id: "2cWBwpqMsDJC1ZUwz813lo",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2736ca5c90113b30c3c43ffb8f4",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e026ca5c90113b30c3c43ffb8f4",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048516ca5c90113b30c3c43ffb8f4",
            width: 64,
          },
        ],
        name: "The Eminem Show",
        release_date: "2002-05-26",
        release_date_precision: "day",
        total_tracks: 20,
        type: "album",
        uri: "spotify:album:2cWBwpqMsDJC1ZUwz813lo",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4otkd9As6YaxxEkIjXPiZ6",
        },
        href: "https://api.spotify.com/v1/albums/4otkd9As6YaxxEkIjXPiZ6",
        id: "4otkd9As6YaxxEkIjXPiZ6",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2732f44aec83b20e40f3baef73c",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e022f44aec83b20e40f3baef73c",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048512f44aec83b20e40f3baef73c",
            width: 64,
          },
        ],
        name: "Music To Be Murdered By",
        release_date: "2020-01-17",
        release_date_precision: "day",
        total_tracks: 20,
        type: "album",
        uri: "spotify:album:4otkd9As6YaxxEkIjXPiZ6",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3MKvhQoFSrR2PrxXXBHe9B",
        },
        href: "https://api.spotify.com/v1/albums/3MKvhQoFSrR2PrxXXBHe9B",
        id: "3MKvhQoFSrR2PrxXXBHe9B",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273b84b0516d901f95461bb5165",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02b84b0516d901f95461bb5165",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851b84b0516d901f95461bb5165",
            width: 64,
          },
        ],
        name: "Music To Be Murdered By - Side B (Deluxe Edition)",
        release_date: "2020-12-18",
        release_date_precision: "day",
        total_tracks: 36,
        type: "album",
        uri: "spotify:album:3MKvhQoFSrR2PrxXXBHe9B",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6t7956yu5zYf5A829XRiHC",
        },
        href: "https://api.spotify.com/v1/albums/6t7956yu5zYf5A829XRiHC",
        id: "6t7956yu5zYf5A829XRiHC",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273dbb3dd82da45b7d7f31b1b42",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02dbb3dd82da45b7d7f31b1b42",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851dbb3dd82da45b7d7f31b1b42",
            width: 64,
          },
        ],
        name: "The Marshall Mathers LP",
        release_date: "2000-05-23",
        release_date_precision: "day",
        total_tracks: 18,
        type: "album",
        uri: "spotify:album:6t7956yu5zYf5A829XRiHC",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/47BiFcV59TQi2s9SkBo2pb",
        },
        href: "https://api.spotify.com/v1/albums/47BiFcV59TQi2s9SkBo2pb",
        id: "47BiFcV59TQi2s9SkBo2pb",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273c08d5fa5c0f1a834acef5100",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02c08d5fa5c0f1a834acef5100",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851c08d5fa5c0f1a834acef5100",
            width: 64,
          },
        ],
        name: "Recovery",
        release_date: "2010-06-18",
        release_date_precision: "day",
        total_tracks: 17,
        type: "album",
        uri: "spotify:album:47BiFcV59TQi2s9SkBo2pb",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR",
        },
        href: "https://api.spotify.com/v1/albums/3HNnxK7NgLXbDoxRZxNWiR",
        id: "3HNnxK7NgLXbDoxRZxNWiR",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273e4073def0c03a91e3fceaf73",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02e4073def0c03a91e3fceaf73",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851e4073def0c03a91e3fceaf73",
            width: 64,
          },
        ],
        name: "Kamikaze",
        release_date: "2018-08-31",
        release_date_precision: "day",
        total_tracks: 13,
        type: "album",
        uri: "spotify:album:3HNnxK7NgLXbDoxRZxNWiR",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6DN7GcZF1HywzrkGN6Eeqk",
        },
        href: "https://api.spotify.com/v1/albums/6DN7GcZF1HywzrkGN6Eeqk",
        id: "6DN7GcZF1HywzrkGN6Eeqk",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273cb66bcc14c6f857c127d5969",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02cb66bcc14c6f857c127d5969",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851cb66bcc14c6f857c127d5969",
            width: 64,
          },
        ],
        name: "The Marshall Mathers LP2 (Deluxe)",
        release_date: "2013-11-05",
        release_date_precision: "day",
        total_tracks: 21,
        type: "album",
        uri: "spotify:album:6DN7GcZF1HywzrkGN6Eeqk",
      },
      {
        album_type: "compilation",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5qENHeCSlwWpEzb25peRmQ",
        },
        href: "https://api.spotify.com/v1/albums/5qENHeCSlwWpEzb25peRmQ",
        id: "5qENHeCSlwWpEzb25peRmQ",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273eab40fc794b88b9d1e012578",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02eab40fc794b88b9d1e012578",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851eab40fc794b88b9d1e012578",
            width: 64,
          },
        ],
        name: "Curtain Call: The Hits (Deluxe Edition)",
        release_date: "2005-12-06",
        release_date_precision: "day",
        total_tracks: 24,
        type: "album",
        uri: "spotify:album:5qENHeCSlwWpEzb25peRmQ",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1kTlYbs28MXw7hwO0NLYif",
        },
        href: "https://api.spotify.com/v1/albums/1kTlYbs28MXw7hwO0NLYif",
        id: "1kTlYbs28MXw7hwO0NLYif",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273726d48d93d02e1271774f023",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02726d48d93d02e1271774f023",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851726d48d93d02e1271774f023",
            width: 64,
          },
        ],
        name: "Encore (Deluxe Version)",
        release_date: "2004-11-12",
        release_date_precision: "day",
        total_tracks: 23,
        type: "album",
        uri: "spotify:album:1kTlYbs28MXw7hwO0NLYif",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
            },
            href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
            id: "7dGJo4pcD2V6oG8kP0tJRR",
            name: "Eminem",
            type: "artist",
            uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/7MZzYkbHL9Tk3O6WeD4Z0Z",
        },
        href: "https://api.spotify.com/v1/albums/7MZzYkbHL9Tk3O6WeD4Z0Z",
        id: "7MZzYkbHL9Tk3O6WeD4Z0Z",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273506c4cc93e5a6234164125e1",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02506c4cc93e5a6234164125e1",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851506c4cc93e5a6234164125e1",
            width: 64,
          },
        ],
        name: "Relapse: Refill",
        release_date: "2009-05-15",
        release_date_precision: "day",
        total_tracks: 29,
        type: "album",
        uri: "spotify:album:7MZzYkbHL9Tk3O6WeD4Z0Z",
      },
    ],
    limit: 10,
    next:
      "https://api.spotify.com/v1/search?query=eminem+&type=album&offset=10&limit=10",
    offset: 0,
    previous: null,
    total: 630,
  },
  artists: {
    href:
      "https://api.spotify.com/v1/search?query=eminem+&type=artist&offset=0&limit=10",
    items: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR",
        },
        followers: {
          href: null,
          total: 42949139,
        },
        genres: ["detroit hip hop", "hip hop", "rap"],
        href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
        id: "7dGJo4pcD2V6oG8kP0tJRR",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/56f4762485066b4ef867b96e16775f2b5b4db277",
            width: 640,
          },
          {
            height: 320,
            url:
              "https://i.scdn.co/image/ad64a7fbc24b31cd84455a1aef34758b94246352",
            width: 320,
          },
          {
            height: 160,
            url:
              "https://i.scdn.co/image/6432e1be8495593f136ad98de6135bb0640ff936",
            width: 160,
          },
        ],
        name: "Eminem",
        popularity: 95,
        type: "artist",
        uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/4JNKmlZrxBwsdUVKakeU6G",
        },
        followers: {
          href: null,
          total: 13,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/4JNKmlZrxBwsdUVKakeU6G",
        id: "4JNKmlZrxBwsdUVKakeU6G",
        images: [],
        name: "Eminemovic",
        popularity: 28,
        type: "artist",
        uri: "spotify:artist:4JNKmlZrxBwsdUVKakeU6G",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/16SfgOBulDFXWORWr5d3qq",
        },
        followers: {
          href: null,
          total: 1513,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/16SfgOBulDFXWORWr5d3qq",
        id: "16SfgOBulDFXWORWr5d3qq",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2737999b090c18df4d3b2e206db",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e027999b090c18df4d3b2e206db",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048517999b090c18df4d3b2e206db",
            width: 64,
          },
        ],
        name: "Emine'm",
        popularity: 2,
        type: "artist",
        uri: "spotify:artist:16SfgOBulDFXWORWr5d3qq",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/4rOaJSGwiRVOuAQ2utQmLE",
        },
        followers: {
          href: null,
          total: 747,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/4rOaJSGwiRVOuAQ2utQmLE",
        id: "4rOaJSGwiRVOuAQ2utQmLE",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273d220abf53e2d090b5bd9bb3f",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02d220abf53e2d090b5bd9bb3f",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851d220abf53e2d090b5bd9bb3f",
            width: 64,
          },
        ],
        name: "Eminemmylou",
        popularity: 2,
        type: "artist",
        uri: "spotify:artist:4rOaJSGwiRVOuAQ2utQmLE",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/715lDaC4Ha9GISfWmHTZWH",
        },
        followers: {
          href: null,
          total: 3267,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/715lDaC4Ha9GISfWmHTZWH",
        id: "715lDaC4Ha9GISfWmHTZWH",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b27351ba62b8c80ebefc438ae11e",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e0251ba62b8c80ebefc438ae11e",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d0000485151ba62b8c80ebefc438ae11e",
            width: 64,
          },
        ],
        name: "Eminemn",
        popularity: 2,
        type: "artist",
        uri: "spotify:artist:715lDaC4Ha9GISfWmHTZWH",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6Dxd9WP0s3TRM2Htt28UQi",
        },
        followers: {
          href: null,
          total: 3712,
        },
        genres: ["venezuelan hip hop"],
        href: "https://api.spotify.com/v1/artists/6Dxd9WP0s3TRM2Htt28UQi",
        id: "6Dxd9WP0s3TRM2Htt28UQi",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b27331e2d03dcfa4b756244de057",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e0231e2d03dcfa4b756244de057",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d0000485131e2d03dcfa4b756244de057",
            width: 64,
          },
        ],
        name: "La EmineMCa",
        popularity: 17,
        type: "artist",
        uri: "spotify:artist:6Dxd9WP0s3TRM2Htt28UQi",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0KT9w8O0PggwZ5ZsAQG0xL",
        },
        followers: {
          href: null,
          total: 34,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/0KT9w8O0PggwZ5ZsAQG0xL",
        id: "0KT9w8O0PggwZ5ZsAQG0xL",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2735369ab27272c93dd6daa787d",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e025369ab27272c93dd6daa787d",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048515369ab27272c93dd6daa787d",
            width: 64,
          },
        ],
        name: "Züleyha Eminem",
        popularity: 0,
        type: "artist",
        uri: "spotify:artist:0KT9w8O0PggwZ5ZsAQG0xL",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3VkqEodd9k0vZdk8dgmOrD",
        },
        followers: {
          href: null,
          total: 0,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/3VkqEodd9k0vZdk8dgmOrD",
        id: "3VkqEodd9k0vZdk8dgmOrD",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b27393cf5d1362f06ed7a234fb7d",
            width: 640,
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e0293cf5d1362f06ed7a234fb7d",
            width: 300,
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d0000485193cf5d1362f06ed7a234fb7d",
            width: 64,
          },
        ],
        name: "La Eminemc'a",
        popularity: 0,
        type: "artist",
        uri: "spotify:artist:3VkqEodd9k0vZdk8dgmOrD",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/5yGSR75I5RwV9TN8aHanjd",
        },
        followers: {
          href: null,
          total: 68,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/5yGSR75I5RwV9TN8aHanjd",
        id: "5yGSR75I5RwV9TN8aHanjd",
        images: [],
        name: "His Emineminence",
        popularity: 0,
        type: "artist",
        uri: "spotify:artist:5yGSR75I5RwV9TN8aHanjd",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/52Qhb96Tc4f0zMSiqqRKr7",
        },
        followers: {
          href: null,
          total: 296,
        },
        genres: [],
        href: "https://api.spotify.com/v1/artists/52Qhb96Tc4f0zMSiqqRKr7",
        id: "52Qhb96Tc4f0zMSiqqRKr7",
        images: [],
        name: "Mc Cavallo feat. Gli Eminem, I Nate Dogg",
        popularity: 2,
        type: "artist",
        uri: "spotify:artist:52Qhb96Tc4f0zMSiqqRKr7",
      },
    ],
    limit: 10,
    next:
      "https://api.spotify.com/v1/search?query=eminem+&type=artist&offset=10&limit=10",
    offset: 0,
    previous: null,
    total: 18,
  },
};
